#!/bin/bash
RESOURCES_ROOT=/vagrant/provision
NODE_TYPE=
HELP=0
ERROR=
while getopts "t:d:h" opt
   do
     case $opt in
        t ) NODE_TYPE=$OPTARG;;
        d ) SETUP_ROOT=$OPTARG;;
				h ) HELP=1;;
				* ) ERROR="Invalid argument: $opt=$OPTARG";;
     esac
done

MASTER_SSH_AUTHORIZED_KEYS=$RESOURCES_ROOT/authorized_keys
HADOOP_RESOURCES=$RESOURCES_ROOT/hadoop
SPARK_RESOURCES=$SPARK_RESOURCES/spark

function validateArguments {

	if [ $HELP -eq 1 ]; then  usage  ; exit 0; fi

	if [ ! -z $ERROR ]; then usage $ERROR; fi

	NODE_TYPE=$(echo $NODE_TYPE | tr '[:upper:]' '[:lower:]')

	if [ -z $NODE_TYPE ]; then usage "No mode specified. It should be either master or slave" ; fi
	if [ $NODE_TYPE != "master" -a  $NODE_TYPE != "slave"  ];
	then
		usage "Node type should be either master or slave"
		exit 1
	fi
	echo "Bootstraping node as: $NODE_TYPE"
}

function setupSSH {
	echo "setup ssh"
	if [ $NODE_TYPE == "master" ]; then
		echo "setup ssh as master"
		setupMaster
	elif [ $NODE_TYPE == "slave" ]; then
		echo "setup ssh as slave"
		setupSlave
	else
		echo "Error in bootstraping node. Unknown mode [$NODE_TYPE] requested"
		exit 1
	fi
}
function setupHadoop {
	echo "setup hadoop"
	if [ -d $HADOOP_RESOURCES ]
	then
		echo "copying hadoop configuration"
		cp -f $HADOOP_RESOURCES/* /usr/local/hadoop/etc/hadoop
	fi
}

function setupSpark {
	echo "setup spark"
	if [ -d $SPARK_RESOURCES ]
	then
		echo "copying spark configuration"
		cp -f $SPARK_RESOURCES/* /usr/local/spark/conf
	fi
}

function setupMaster {
	echo "creating keys"
	createSSHKey
	exportSSHKey
}

function setupSlave {
	echo "append authorized keys"
	appendAuthorizedKeys
}


function createSSHKey {
	echo "generating ssh keys for user $USER"
	ssh-keygen -t rsa -P "" -f ~/.ssh/id_rsa
	cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
}

function exportSSHKey {
	echo "export public ssh key"
	cat ~/.ssh/id_rsa.pub >> $MASTER_SSH_AUTHORIZED_KEYS
}

function appendAuthorizedKeys {
	FILE=~/.ssh/authorized_keys

	if [  -e $MASTER_SSH_AUTHORIZED_KEYS ];	then
		cat $MASTER_SSH_AUTHORIZED_KEYS >> $FILE
	fi
	sort -o $FILE -u $FILE

	chmod 600 $FILE
}
function usage {
	if [ ! -z "$1" ]; then echo "ERROR: $1"; fi

	cat <<-__USAGE__
Usage:
  bootstram-node -t <node-type> [-d <resource-dir>]

OPTIONS:
  -t <node-type>    : Required. Type of this node. It should be either 'master' or 'slave'
  -d <resource-dir> : Location of provisioning resource directory.
                      This should contain 'hadoop' and 'spark' folder.
                      Default: /vagrant/provision
__USAGE__

	if [ ! -z "$1" ]; then exit 1; fi
}

validateArguments
setupSSH
setupHadoop
setupSpark
